cp ../../hp/shib/site/index.html .
cp ../../hp/shib/site/registration.html .
cp ../../hp/shib/site/registration_mobile_number.html .
cp ../../hp/shib/site/registration_mobile_verify.html .
cp ../../hp/shib/site/enter_name.html .
cp ../../hp/shib/site/demographics.html .
cp ../../hp/shib/site/registration_thx.html .
cp ../../hp/shib/site/registration_local_address.html .
cp ../../hp/shib/site/home.html .
cp ../../hp/shib/site/testing_how_to.html .
cp ../../hp/shib/site/my_testing.html .
cp ../../hp/shib/site/find_test_site.html .
cp ../../hp/shib/site/find_test_site_slots.html .
cp ../../hp/shib/site/find_test_site_slot_booked.html .
cp ../../hp/shib/site/find_test_site_slot_full.html .
cp ../../hp/shib/site/find_test_site_confirmtime.html .
cp ../../hp/shib/site/reservation.html .
cp ../../hp/shib/site/my_reservations.html .
cp ../../hp/shib/site/cancel_thx.html .
cp ../../hp/shib/site/scan_complete.html .
cp ../../hp/shib/site/start_new_test.html .
cp ../../hp/shib/site/my_schedule.html .
cp ../../hp/shib/site/class_search.html .
cp ../../hp/shib/site/class_details.html .
cp ../../hp/shib/site/support.html .
cp ../../hp/shib/site/error_400.html .
cp ../../hp/shib/site/error_500.html .
